services:
  frontend:
    build:
      context: frontend
      dockerfile: docker/Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/frontend/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: backend
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app

networks:
  default:
    name: bychance-job-network
