FROM python:3.13

WORKDIR /app/backend

COPY ./requirements.txt ./

RUN pip install --no-cache-dir --upgrade -r ./requirements.txt

COPY ./src ./

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--reload"]
