name: Backend Lint and Format Check

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'backend/**'
      - '.github/workflows/backend-lint.yml'

jobs:
  ruff-lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: lint check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ruff check . | reviewdog \
            -f=flake8 \
            -name="ruff(lint)" \
            -reporter=github-pr-review \
            -filter-mode=file \
            -fail-on-error=true \
            -level=warning

  ruff-check-diff:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: ruff check diff
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ruff check --diff . | reviewdog \
            -f=diff \
            -f.diff.strip=0 \
            -name="ruff(diff)" \
            -reporter=github-pr-review \
            -filter-mode=file \
            -fail-on-error=true \
            -level=warning

  ruff-format-diff:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: ruff format diff
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ruff format --diff --check . 2>&1 | reviewdog \
            -f=diff \
            -f.diff.strip=0 \
            -name="ruff format" \
            -reporter=github-pr-review \
            -filter-mode=file \
            -fail-on-error=true \
            -level=warning

  mypy:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Reviewdog
        uses: reviewdog/action-setup@e04ffabe3898a0af8d0fb1af00c188831c4b5893 # v1.3.2
        with:
          reviewdog_version: latest

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: mypy
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mypy . --ignore-missing-imports \
            | reviewdog -f="mypy" \
            -name="mypy" \
            -reporter="github-pr-review" \
            -filter-mode="file" \
            -fail-on-error="true" \
            -level="error"
